/**
 * demo.ts — Demo данные для режима без Supabase
 * Реалистичные данные из Таджикистана (Худжанд)
 */

import type { Product, Store, ServiceCenter, Order, Car } from "./types";

export const DEMO_CARS: Car[] = [
  {
    id: "demo-car-1",
    make: "Toyota",
    model: "Camry",
    year: "2019",
    color: "Белый",
    plate: "TJ 0011 AB",
    mileage: 78000,
    addedAt: "2024-01-15T10:00:00Z",
  },
];

export const DEMO_STORES: Store[] = [
  {
    id: "auto-parts-khujand",
    name: "АвтоЗапчасти Худжанд",
    city: "Худжанд",
    address: "пр-т Исмоили Сомони, 12",
    category: "Автозапчасти",
    logo_url: "",
    phone: "+992 92 777 00 01",
    rating: 4.8,
    status: "active",
  },
  {
    id: "battery-hub-sughd",
    name: "АКБ Центр Согд",
    city: "Худжанд",
    address: "ул. Ленина, 45",
    category: "Аккумуляторы",
    logo_url: "",
    phone: "+992 93 500 10 10",
    rating: 4.6,
    status: "active",
  },
];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "demo-p1",
    store_id: "auto-parts-khujand",
    title: "Масло моторное Mobil 5W-30",
    category: "Масла",
    category_id: "oils",
    price: 185,
    old_price: 210,
    image_url: "https://images.unsplash.com/photo-1635430906024-7cb0a82b7abb?w=400&q=80",
    brand: "Mobil",
    sku: "MOB-5W30-4L",
    stock_qty: 24,
    description: "Синтетическое моторное масло. Объём 4 литра.",
    badge: "Хит",
    rating: 4.9,
    reviews_count: 156,
    publish_status: "active",
    delivery_available: true,
  },
  {
    id: "demo-p2",
    store_id: "auto-parts-khujand",
    title: "Фильтр масляный Bosch",
    category: "Фильтры",
    category_id: "filters",
    price: 42,
    image_url: "https://images.unsplash.com/photo-1581244277943-fe4a9c777540?w=400&q=80",
    brand: "Bosch",
    sku: "BOS-OF-001",
    stock_qty: 80,
    description: "Оригинальный масляный фильтр.",
    rating: 4.7,
    reviews_count: 89,
    publish_status: "active",
    delivery_available: true,
  },
  {
    id: "demo-p3",
    store_id: "auto-parts-khujand",
    title: "Тормозные колодки Brembo",
    category: "Тормоза",
    category_id: "brakes",
    price: 320,
    old_price: 380,
    image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
    brand: "Brembo",
    sku: "BREM-P24-002",
    stock_qty: 12,
    description: "Передние тормозные колодки. Комплект 4 шт.",
    badge: "Скидка",
    rating: 4.8,
    reviews_count: 234,
    publish_status: "active",
    delivery_available: true,
  },
  {
    id: "demo-p4",
    store_id: "battery-hub-sughd",
    title: "АКБ Varta 60Ah",
    category: "Аккумуляторы",
    category_id: "batteries",
    price: 520,
    image_url: "https://images.unsplash.com/photo-1580274455191-1c62238fa333?w=400&q=80",
    brand: "Varta",
    sku: "VRT-60-001",
    stock_qty: 8,
    description: "Аккумулятор 60Ач. Гарантия 2 года.",
    badge: "Популярное",
    rating: 4.9,
    reviews_count: 445,
    publish_status: "active",
    delivery_available: false,
  },
  {
    id: "demo-p5",
    store_id: "auto-parts-khujand",
    title: "Свечи зажигания NGK (4 шт.)",
    category: "Двигатель",
    category_id: "engine",
    price: 95,
    old_price: 110,
    image_url: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=400&q=80",
    brand: "NGK",
    stock_qty: 45,
    description: "Комплект свечей зажигания 4 шт.",
    rating: 4.6,
    reviews_count: 67,
    publish_status: "active",
    delivery_available: true,
  },
  {
    id: "demo-p6",
    store_id: "auto-parts-khujand",
    title: "Щётки стеклоочистителя Bosch AeroTwin",
    category: "Аксессуары",
    category_id: "accessories",
    price: 210,
    old_price: 245,
    image_url: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400&q=80",
    brand: "Bosch",
    stock_qty: 30,
    description: "Бескаркасные щётки. Комплект 2 шт.",
    badge: "Скидка",
    rating: 4.8,
    reviews_count: 73,
    publish_status: "active",
    delivery_available: true,
  },
];

export const DEMO_SERVICES: ServiceCenter[] = [
  {
    id: "demo-sc-1",
    name: "АвтоМастер Премиум",
    category: "СТО",
    description: "Современное СТО с прозрачной сметой и быстрым ремонтом.",
    address: "пр-т Исмоили Сомони, 28",
    city: "Худжанд",
    lat: 40.2837,
    lng: 69.6213,
    working_hours: "08:00 — 20:00",
    phones: ["+992 92 777 21 10"],
    photos: ["https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=800&q=80"],
    logo_url: "",
    rating: 4.8,
    reviews_count: 234,
    boxes_count: 6,
    status: "active",
  },
  {
    id: "demo-sc-2",
    name: "ШиноМонтаж 24/7",
    category: "Шиномонтаж",
    description: "Быстрый шиномонтаж, балансировка, ремонт колёс.",
    address: "8 мкр, рядом с кольцом",
    city: "Худжанд",
    lat: 40.2791,
    lng: 69.6188,
    working_hours: "Круглосуточно",
    phones: ["+992 93 555 44 00"],
    photos: ["https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&q=80"],
    logo_url: "",
    rating: 4.9,
    reviews_count: 167,
    boxes_count: 4,
    status: "active",
  },
  {
    id: "demo-sc-3",
    name: "Detail Garage Premium",
    category: "Детейлинг",
    description: "Профессиональный детейлинг, химчистка, керамика.",
    address: "ул. Гагарина, 14",
    city: "Худжанд",
    lat: 40.2765,
    lng: 69.6240,
    working_hours: "09:00 — 21:00",
    phones: ["+992 90 440 88 11"],
    photos: ["https://images.unsplash.com/photo-1607861716497-e65ab29fc7ac?w=800&q=80"],
    logo_url: "",
    rating: 4.7,
    reviews_count: 445,
    boxes_count: 3,
    status: "active",
  },
];

export const DEMO_ORDERS: Order[] = [
  {
    id: "demo-order-1",
    store_id: "auto-parts-khujand",
    customer_name: "Фарход Рахимов",
    customer_phone: "+992 92 777 00 00",
    items: [
      { product_id: "demo-p1", product_title: "Масло Mobil 5W-30", quantity: 2, unit_price: 185 },
      { product_id: "demo-p2", product_title: "Фильтр Bosch", quantity: 1, unit_price: 42 },
    ],
    total_amount: 412,
    status: "confirmed",
    delivery_type: "delivery",
    delivery_address: "Худжанд, мкр 19, д. 47",
    payment_status: "paid",
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-order-2",
    store_id: "battery-hub-sughd",
    customer_name: "Санобар Назарова",
    customer_phone: "+992 93 500 20 20",
    items: [
      { product_id: "demo-p4", product_title: "АКБ Varta 60Ah", quantity: 1, unit_price: 520 },
    ],
    total_amount: 520,
    status: "new",
    delivery_type: "pickup",
    payment_status: "pending",
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
];
